In [3]:
import pandas as pd 
import numpy as np

In [4]:
# import csv file
rates = pd.read_csv("/Users/victoriaguo/Desktop/DS 4002/project2/10year_rates.csv")

In [5]:
rates.head()

,Record Date,Security Type Description,Security Description,Average Interest Rate Amount,Source Line Number,Fiscal Year,Fiscal Quarter Number,Calendar Year,Calendar Quarter Number,Calendar Month Number,Calendar Day Number
0,1/31/24,Marketable,Treasury Bills,5.411,1,2024,2,2024,1,1,31
1,1/31/24,Marketable,Treasury Notes,2.340,2,2024,2,2024,1,1,31
2,1/31/24,Marketable,Treasury Bonds,3.106,3,2024,2,2024,1,1,31
3,1/31/24,Marketable,Treasury Inflation-Protected Securities (TIPS),0.648,4,2024,2,2024,1,1,31
4,1/31/24,Marketable,Treasury Floating Rate Notes (FRN),5.543,5,2024,2,2024,1,1,31

In [15]:
# only keep rows that correspond to Treasury Bills, Bonds, and Notes
conditions = (rates['Security Description'] == 'Treasury Bills') | (rates['Security Description'] == 'Treasury Notes') | (rates['Security Description'] == 'Treasury Bonds')

rates_real = rates[conditions]

In [7]:
rates_real.head()

,Record Date,Security Type Description,Security Description,Average Interest Rate Amount,Source Line Number,Fiscal Year,Fiscal Quarter Number,Calendar Year,Calendar Quarter Number,Calendar Month Number,Calendar Day Number
0,1/31/24,Marketable,Treasury Bills,5.411,1,2024,2,2024,1,1,31
1,1/31/24,Marketable,Treasury Notes,2.340,2,2024,2,2024,1,1,31
2,1/31/24,Marketable,Treasury Bonds,3.106,3,2024,2,2024,1,1,31
17,12/31/23,Marketable,Treasury Bills,5.437,1,2024,1,2023,4,12,31
18,12/31/23,Marketable,Treasury Notes,2.272,2,2024,1,2023,4,12,31

In [16]:
# keep necessary columns: security description, record date, and average interest rate amount
columns_keep = ['Security Description', 'Record Date', 'Average Interest Rate Amount']

# remove na's 
rates_final = rates_real[columns_keep].dropna()

In [14]:
rates_final.info()
rates_final.head()

<class 'pandas.core.frame.DataFrame'>
Index: 360 entries, 0 to 1988
Data columns (total 3 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Security Description          360 non-null    object
 1   Record Date                   360 non-null    object
 2   Average Interest Rate Amount  360 non-null    float64
dtypes: float64(1), object(2)
memory usage: 11.2+ KB

   Security Description Record Date  Average Interest Rate Amount
0        Treasury Bills     1/31/24                         5.411
1        Treasury Notes     1/31/24                         2.340
2        Treasury Bonds     1/31/24                         3.106
17       Treasury Bills    12/31/23                         5.437
18       Treasury Notes    12/31/23                         2.272

In [17]:
# export data to csv file

rates_final.to_csv("/Users/victoriaguo/Desktop/DS 4002/project2/final_data.csv")